name: gh-metrics
on:
  # Schedule updates (midnight UTC)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: upsatwal/gh-metrics@main
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METERICS_TOKEN }} #misspelt token, oops
          # output_action: commit
          # committer_branch: main
          # commiter_message: "🛠 Chore: Update metrics"
          # config_padding: 0, -1% # keeps breaking

          # config_output: markdown-pdf # not supported with these plugins
          # config_base64: yes # for pdf rendering

          # Options
          user: upsatwal
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_presets: "@lunar-red" # red

          # config_presets: https://github.com/UPSAtwal/UPSAtwal/raw/main/metrics-preset-catpucchin.yml
          config_timezone: Asia/Kolkata
          plugin_achievements: no
          # plugin_achievements_display: detailed
          # plugin_achievements_secrets: yes
          # plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_isocalendar: no
          # plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes,percentage
          # plugin_languages_indepth: yes # needs additional permissions
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          # plugin_people: yes
          # plugin_people_limit: 24
          # plugin_people_size: 28
          # plugin_people_types: followers
          plugin_repositories: yes
          plugin_repositories_order: pinned, featured, starred, random
          plugin_repositories_pinned: 4
          plugin_repositories_affiliations: owner, collaborator #no middle ground for organization_member
          # plugin_stargazers: yes
          # plugin_stargazers_charts: yes
          # plugin_stargazers_charts_type: classic
          # plugin_stargazers_days: 14
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, projects-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: upsatwal
          
          #plugin_activity: yes
          #plugin_activity_limit: 8
          #plugin_activity_days: 0
          #plugin_activity_filter: issue, pr, release, fork, review, ref/create
          #plugin_activity_visibility: public
          
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://uday.codes
